"""
Event Forwarder — HTTP POST to claw-server.

Unified egress for all events generated by the minimax plugin and gateway
hooks. Each event is serialized as JSON and sent to:

    {claw_server_url}/hermes/event

with the X-Claw-Sandbox-Key header for authentication.
"""

from __future__ import annotations

import json
import logging
import time
import uuid
from typing import Any, Dict, Optional
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

from .config import get_claw_server_url, get_sandbox_key
from .logger import log_fwd_resp, log_fwd_send
from .types import ForwardResult, HermesEvent

logger = logging.getLogger(__name__)

LOG_PREFIX = "[MMLOG]"

_TIMEOUT_SECONDS = 10
_MAX_RETRIES = 2
_RETRY_DELAY = 0.5


def _build_headers(sandbox_key: str, trace_id: str = "") -> Dict[str, str]:
    return {
        "Content-Type": "application/json",
        "X-Claw-Sandbox-Key": sandbox_key,
        "X-Trace-Id": trace_id or uuid.uuid4().hex,
    }


class EventForwarder:
    """Stateless HTTP forwarder that sends HermesEvent payloads to claw-server."""

    def __init__(self) -> None:
        self._consecutive_failures = 0

    def forward(self, event: HermesEvent) -> ForwardResult:
        """Send an event to claw-server. Returns the result (never raises)."""
        sandbox_key = event.sandbox_key or get_sandbox_key()
        base_url = get_claw_server_url()
        if not base_url:
            logger.warning("%s[FWD:SEND] claw_server_url not configured, dropping type=%s", LOG_PREFIX, event.type)
            return ForwardResult(ok=False, error="claw_server_url not configured")

        endpoint = f"{base_url}/hermes/event"
        if not event.sandbox_key:
            event.sandbox_key = sandbox_key
        if not event.timestamp:
            event.timestamp = int(time.time() * 1000)

        trace_id = uuid.uuid4().hex
        headers = _build_headers(sandbox_key, trace_id)
        if event.run_id:
            headers["X-Run-Id"] = event.run_id
        if event.session_id:
            headers["X-Session-Id"] = event.session_id

        body_dict = event.to_dict()
        body = json.dumps(body_dict, ensure_ascii=False, default=str).encode("utf-8")

        # Log the outbound event before sending
        log_fwd_send(
            logger,
            event_type=event.type,
            run_id=event.run_id or "",
            session_id=event.session_id or "",
            trace_id=trace_id,
            payload=body_dict,
        )

        start = time.perf_counter()
        for attempt in range(1, _MAX_RETRIES + 1):
            try:
                req = Request(endpoint, data=body, headers=headers, method="POST")
                with urlopen(req, timeout=_TIMEOUT_SECONDS) as resp:
                    resp_body = resp.read().decode("utf-8", errors="replace")
                    try:
                        parsed = json.loads(resp_body)
                    except Exception:
                        parsed = {"raw": resp_body}

                    self._consecutive_failures = 0
                    blocked = parsed.get("blocked", False) if isinstance(parsed, dict) else False
                    dur_ms = int((time.perf_counter() - start) * 1000)
                    log_fwd_resp(
                        logger,
                        event_type=event.type,
                        run_id=event.run_id or "",
                        trace_id=trace_id,
                        ok=True,
                        http_status=resp.status,
                        dur_ms=dur_ms,
                        body=parsed,
                    )
                    return ForwardResult(
                        ok=True,
                        status_code=resp.status,
                        body=parsed,
                        blocked=blocked,
                    )
            except HTTPError as exc:
                resp_text = ""
                try:
                    resp_text = exc.read().decode("utf-8", errors="replace")
                except Exception:
                    pass
                dur_ms = int((time.perf_counter() - start) * 1000)
                log_fwd_resp(
                    logger,
                    event_type=event.type,
                    run_id=event.run_id or "",
                    trace_id=trace_id,
                    ok=False,
                    http_status=exc.code,
                    dur_ms=dur_ms,
                    error=f"HTTP {exc.code} (attempt {attempt}/{_MAX_RETRIES}): {resp_text[:200]}",
                )
                if attempt < _MAX_RETRIES:
                    time.sleep(_RETRY_DELAY * attempt)
            except (URLError, OSError) as exc:
                dur_ms = int((time.perf_counter() - start) * 1000)
                log_fwd_resp(
                    logger,
                    event_type=event.type,
                    run_id=event.run_id or "",
                    trace_id=trace_id,
                    ok=False,
                    http_status=None,
                    dur_ms=dur_ms,
                    error=f"Network error (attempt {attempt}/{_MAX_RETRIES}): {exc}",
                )
                if attempt < _MAX_RETRIES:
                    time.sleep(_RETRY_DELAY * attempt)
            except Exception as exc:
                dur_ms = int((time.perf_counter() - start) * 1000)
                log_fwd_resp(
                    logger,
                    event_type=event.type,
                    run_id=event.run_id or "",
                    trace_id=trace_id,
                    ok=False,
                    http_status=None,
                    dur_ms=dur_ms,
                    error=f"Unexpected: {exc}",
                )
                logger.error("%s[FWD:RESP] unexpected error: %s", LOG_PREFIX, exc, exc_info=True)
                break

        self._consecutive_failures += 1
        return ForwardResult(ok=False, error=f"failed after {_MAX_RETRIES} attempts")

    def forward_dict(self, data: Dict[str, Any]) -> ForwardResult:
        """Convenience: forward a plain dict by converting to HermesEvent."""
        known_fields = set(HermesEvent.__dataclass_fields__.keys())
        event_kwargs = {k: v for k, v in data.items() if k in known_fields}
        extra_keys = set(data.keys()) - known_fields
        event = HermesEvent(**event_kwargs)
        if extra_keys:
            event.metadata = event.metadata or {}
            for k in extra_keys:
                event.metadata[k] = data[k]
        return self.forward(event)


def generate_msg_id() -> Optional[int]:
    """Request a snowflake msg_id from claw-server."""
    base_url = get_claw_server_url()
    sandbox_key = get_sandbox_key()
    if not base_url or not sandbox_key:
        return None

    endpoint = f"{base_url}/internal/generate_msg_id"
    trace_id = uuid.uuid4().hex
    headers = _build_headers(sandbox_key, trace_id)

    payload = json.dumps({"trace_id": trace_id}).encode("utf-8")

    try:
        req = Request(endpoint, data=payload, headers=headers, method="POST")
        with urlopen(req, timeout=5) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            msg_id = data.get("msg_id")
            logger.info(
                "%s[FWD:SEND] generate_msg_id: trace=%s msg_id=%s",
                LOG_PREFIX, trace_id, msg_id,
            )
            return msg_id
    except Exception as exc:
        logger.warning("%s[FWD:RESP] generate_msg_id failed: trace=%s err=%s", LOG_PREFIX, trace_id, exc)
        return None
