class RBACPolicy:
    def __init__(self, rules):
        self.rules = rules

    def is_allowed(self, role: str, action: str) -> bool:
        return action in self.rules.get(role, set())


def build_default_rbac_policy() -> RBACPolicy:
    return RBACPolicy(
        {
            "admin": {
                "control_plane.run",
                "control_plane.dispatch",
                "provider.execute_sensitive",
                "provider.openclaw.live",
                "monitor.export",
                "query.workflow",
                "query.workflow.manage",
                "query.handoff",
                "query.handoff.manage",
                "query.knowledge",
                "query.knowledge.manage",
                "query.audit.read",
                "tool.read.generic",
                "tool.read.knowledge",
                "tool.read.handoff",
                "tool.read.workflow",
                "tool.read.file",
                "tool.read.bus",
                "tool.read.search",
                "tool.write.generic",
                "tool.write.file",
                "tool.route",
                "tool.dispatch",
                "tool.execute.command",
                "tool.execute.tests",
                "tool.execute.linter",
                "tool.execute.apitests",
                "tool.generate.code",
                "tool.generate.controller",
                "tool.generate.service",
                "tool.generate.mapper",
                "tool.generate.vue",
                "tool.generate.apiclient",
                "tool.generate.archdoc",
                "tool.generate.ddl",
                "tool.generate.testcases",
                "tool.generate.dockerfile",
                "tool.generate.k8s",
                "tool.generate.designspec",
                "tool.generate.prd",
                "tool.review.api",
                "tool.analyze.sql",
            },
            "operator": {
                "control_plane.run",
                "control_plane.dispatch",
                "monitor.export",
                "query.workflow",
                "query.workflow.manage",
                "query.handoff",
                "query.handoff.manage",
                "query.knowledge",
                "query.knowledge.manage",
                "query.audit.read",
                "tool.read.generic",
                "tool.read.knowledge",
                "tool.read.handoff",
                "tool.read.workflow",
                "tool.read.file",
                "tool.read.bus",
                "tool.read.search",
                "tool.write.generic",
                "tool.write.file",
                "tool.route",
                "tool.dispatch",
                "tool.execute.command",
                "tool.execute.tests",
                "tool.execute.linter",
                "tool.execute.apitests",
                "tool.generate.code",
                "tool.generate.controller",
                "tool.generate.service",
                "tool.generate.mapper",
                "tool.generate.vue",
                "tool.generate.apiclient",
                "tool.generate.archdoc",
                "tool.generate.ddl",
                "tool.generate.testcases",
                "tool.generate.dockerfile",
                "tool.generate.k8s",
                "tool.generate.designspec",
                "tool.generate.prd",
                "tool.review.api",
                "tool.analyze.sql",
            },
            "viewer": {
                "monitor.read",
                "query.workflow",
                "query.handoff",
                "query.knowledge",
                "query.audit.read",
                "tool.read.generic",
                "tool.read.knowledge",
                "tool.read.handoff",
                "tool.read.workflow",
                "tool.read.file",
                "tool.read.bus",
                "tool.read.search",
            },
        }
    )
